[project]
name = "explore-polars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.1",
    "polars>=1.19.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
